// ── 1000+ вопросов для автобиографии, по ~84 на главу ──
// Каждый вопрос привязан к главе и содержит ru/en версии.
// Вопросы написаны так, чтобы потомки с интересом читали ответы предков.

export interface MappedQuestion {
  ru: string;
  en: string;
  chapter: string;
}

export const questionPool: MappedQuestion[] = [
  // ════════════════════════════════════════
  // CHILDHOOD (84 вопросов)
  // ════════════════════════════════════════
  { chapter: "childhood", ru: "Какой момент из детства вы никогда не забудете?", en: "What childhood moment will you never forget?" },
  { chapter: "childhood", ru: "Какая игра или занятие было вашим любимым в детстве?", en: "What was your favorite game or activity as a child?" },
  { chapter: "childhood", ru: "Кто из взрослых оказал на вас наибольшее влияние в детстве?", en: "Which adult had the biggest influence on you as a child?" },
  { chapter: "childhood", ru: "Какой запах или вкус напоминает вам о детстве?", en: "What smell or taste reminds you of childhood?" },
  { chapter: "childhood", ru: "Как выглядел дом, где вы выросли?", en: "What did the house you grew up in look like?" },
  { chapter: "childhood", ru: "Какой была ваша любимая еда в детстве?", en: "What was your favorite food as a child?" },
  { chapter: "childhood", ru: "Какую историю вам рассказывали перед сном?", en: "What story were you told before bedtime?" },
  { chapter: "childhood", ru: "Чего вы больше всего боялись в детстве?", en: "What scared you most as a child?" },
  { chapter: "childhood", ru: "Какой подарок из детства вы помните до сих пор?", en: "What childhood gift do you still remember?" },
  { chapter: "childhood", ru: "Какой школьный учитель повлиял на вашу жизнь?", en: "Which school teacher influenced your life?" },
  { chapter: "childhood", ru: "Какой была ваша первая дружба?", en: "What was your first friendship like?" },
  { chapter: "childhood", ru: "Как вы проводили летние каникулы?", en: "How did you spend summer vacations?" },
  { chapter: "childhood", ru: "Какую шалость вы до сих пор помните?", en: "What mischief do you still remember?" },
  { chapter: "childhood", ru: "Какой мультфильм или фильм был вашим любимым в детстве?", en: "What cartoon or movie was your favorite as a child?" },
  { chapter: "childhood", ru: "Какую книгу вы прочитали первой?", en: "What was the first book you read?" },
  { chapter: "childhood", ru: "Как выглядел ваш двор или улица?", en: "What did your yard or street look like?" },
  { chapter: "childhood", ru: "Кем вы мечтали стать, когда вырастете?", en: "What did you dream of becoming when you grew up?" },
  { chapter: "childhood", ru: "Какой предмет в школе вы любили больше всего?", en: "What school subject did you love the most?" },
  { chapter: "childhood", ru: "Что вас радовало в обычный день?", en: "What made you happy on an ordinary day?" },
  { chapter: "childhood", ru: "Какую песню вы помните из детства?", en: "What song do you remember from childhood?" },
  { chapter: "childhood", ru: "Было ли у вас домашнее животное? Расскажите о нём.", en: "Did you have a pet? Tell about it." },
  { chapter: "childhood", ru: "Какой праздник вы любили больше всего в детстве?", en: "What holiday did you love the most as a child?" },
  { chapter: "childhood", ru: "Как наказывали детей в вашей семье?", en: "How were children disciplined in your family?" },
  { chapter: "childhood", ru: "Какая детская травма или обида вас изменила?", en: "What childhood hurt or injury changed you?" },
  { chapter: "childhood", ru: "Что вы коллекционировали в детстве?", en: "What did you collect as a child?" },
  { chapter: "childhood", ru: "Какие правила были в вашем доме?", en: "What rules were in your home?" },
  { chapter: "childhood", ru: "Какой двор или парк был вашим любимым местом?", en: "What yard or park was your favorite place?" },
  { chapter: "childhood", ru: "Кто был вашим героем в детстве?", en: "Who was your hero as a child?" },
  { chapter: "childhood", ru: "Какой момент вы хотели бы пережить снова?", en: "What moment would you want to relive?" },
  { chapter: "childhood", ru: "Как вы добирались до школы?", en: "How did you get to school?" },
  { chapter: "childhood", ru: "Какую одежду вы носили в детстве?", en: "What clothes did you wear as a child?" },
  { chapter: "childhood", ru: "Какой звук ассоциируется у вас с детством?", en: "What sound do you associate with childhood?" },
  { chapter: "childhood", ru: "Что вы делали после школы?", en: "What did you do after school?" },
  { chapter: "childhood", ru: "Какой секрет вы хранили в детстве?", en: "What secret did you keep as a child?" },
  { chapter: "childhood", ru: "Какой самый дерзкий поступок вы совершили в детстве?", en: "What was the boldest thing you did as a child?" },
  { chapter: "childhood", ru: "Где вы прятались, когда хотели побыть одни?", en: "Where did you hide when you wanted to be alone?" },
  { chapter: "childhood", ru: "Какой сон из детства вы помните?", en: "What childhood dream do you remember?" },
  { chapter: "childhood", ru: "Как выглядела ваша комната?", en: "What did your room look like?" },
  { chapter: "childhood", ru: "Какая игрушка была вашей самой любимой?", en: "What toy was your absolute favorite?" },
  { chapter: "childhood", ru: "Что готовила ваша бабушка?", en: "What did your grandmother cook?" },
  { chapter: "childhood", ru: "Какой первый фильм вы посмотрели в кинотеатре?", en: "What was the first movie you saw in a theater?" },
  { chapter: "childhood", ru: "Какие слова родителей вы запомнили навсегда?", en: "What words of your parents do you remember forever?" },
  { chapter: "childhood", ru: "С кем вы дрались или ссорились в детстве?", en: "Who did you fight or argue with as a child?" },
  { chapter: "childhood", ru: "Какой урок жизни вы получили в детстве?", en: "What life lesson did you learn in childhood?" },
  { chapter: "childhood", ru: "Как вас называли в детстве — было ли у вас прозвище?", en: "What were you called as a child — did you have a nickname?" },
  { chapter: "childhood", ru: "Какой новогодний или рождественский праздник вы помните лучше всего?", en: "What New Year or Christmas do you remember best?" },
  { chapter: "childhood", ru: "Какая погода или время года ассоциируется с детством?", en: "What weather or season do you associate with childhood?" },
  { chapter: "childhood", ru: "Во что вы играли с соседскими детьми?", en: "What did you play with the neighborhood kids?" },
  { chapter: "childhood", ru: "Какую ошибку вы совершили в детстве и чему она научила?", en: "What mistake did you make as a child and what did it teach you?" },
  { chapter: "childhood", ru: "Какая поездка из детства запомнилась вам больше всего?", en: "What childhood trip was most memorable?" },
  { chapter: "childhood", ru: "Как вы узнали что-то важное о мире впервые?", en: "How did you learn something important about the world for the first time?" },
  { chapter: "childhood", ru: "Какой момент детства научил вас сочувствию?", en: "What childhood moment taught you empathy?" },
  { chapter: "childhood", ru: "Что вы делали в дождливые дни?", en: "What did you do on rainy days?" },
  { chapter: "childhood", ru: "Какой взрослый поступок вас удивил в детстве?", en: "What adult action surprised you as a child?" },
  { chapter: "childhood", ru: "Какой вкус мороженого вы помните из детства?", en: "What ice cream flavor do you remember from childhood?" },
  { chapter: "childhood", ru: "Где проходили ваши семейные обеды?", en: "Where did your family dinners take place?" },
  { chapter: "childhood", ru: "Какой момент вы хотели бы рассказать своим внукам?", en: "What moment would you want to tell your grandchildren about?" },
  { chapter: "childhood", ru: "Были ли у вас воображаемые друзья?", en: "Did you have imaginary friends?" },
  { chapter: "childhood", ru: "Что вам нравилось рисовать или мастерить?", en: "What did you like to draw or craft?" },
  { chapter: "childhood", ru: "Какое место из детства вы хотели бы посетить снова?", en: "What childhood place would you want to visit again?" },
  { chapter: "childhood", ru: "Как вы впервые заработали деньги?", en: "How did you first earn money?" },
  { chapter: "childhood", ru: "Какая семейная привычка из детства стала вашей?", en: "What family habit from childhood became yours?" },
  { chapter: "childhood", ru: "Какой момент заставил вас почувствовать себя взрослым?", en: "What moment made you feel grown up?" },
  { chapter: "childhood", ru: "Что вы знали наизусть — стихи, песни, считалки?", en: "What did you know by heart — poems, songs, counting rhymes?" },
  { chapter: "childhood", ru: "Какой школьный день вы не забудете?", en: "What school day will you never forget?" },
  { chapter: "childhood", ru: "Какой запрет родителей казался вам несправедливым?", en: "What parental rule seemed unfair to you?" },
  { chapter: "childhood", ru: "Какой случай в детстве был по-настоящему опасным?", en: "What childhood incident was truly dangerous?" },
  { chapter: "childhood", ru: "Что вас вдохновляло в детстве?", en: "What inspired you as a child?" },
  { chapter: "childhood", ru: "Какую тайну двора или школы вы разгадали?", en: "What secret of the yard or school did you uncover?" },
  { chapter: "childhood", ru: "Какое блюдо из детства вы готовите до сих пор?", en: "What childhood dish do you still cook?" },
  { chapter: "childhood", ru: "Как вы помогали по дому в детстве?", en: "How did you help around the house as a child?" },
  { chapter: "childhood", ru: "Какой момент разочарования вы пережили в детстве?", en: "What moment of disappointment did you experience as a child?" },
  { chapter: "childhood", ru: "Как выглядел мир из окна вашей детской комнаты?", en: "What did the world look like from your childhood room window?" },
  { chapter: "childhood", ru: "Кого из одноклассников вы помните до сих пор?", en: "Which classmate do you still remember?" },
  { chapter: "childhood", ru: "Какие традиции двора были в вашем детстве?", en: "What neighborhood traditions existed in your childhood?" },
  { chapter: "childhood", ru: "Что вы чувствовали первого сентября?", en: "What did you feel on the first day of school?" },
  { chapter: "childhood", ru: "Какой момент из детства научил вас быть храбрым?", en: "What childhood moment taught you to be brave?" },
  { chapter: "childhood", ru: "Какую историю из детства ваши родители пересказывают до сих пор?", en: "What childhood story do your parents still retell?" },
  { chapter: "childhood", ru: "Какой предмет из детства вы храните до сих пор?", en: "What childhood object do you still keep?" },
  { chapter: "childhood", ru: "Как звучал голос человека, которого вы любили больше всего в детстве?", en: "What did the voice of the person you loved most in childhood sound like?" },
  { chapter: "childhood", ru: "Какое открытие вы сделали в детстве?", en: "What discovery did you make as a child?" },
  { chapter: "childhood", ru: "Что бы вы сказали себе-ребёнку?", en: "What would you say to your child self?" },
  { chapter: "childhood", ru: "Какое лето было самым счастливым?", en: "What summer was the happiest?" },
  { chapter: "childhood", ru: "Каким был ваш лучший день рождения в детстве?", en: "What was your best childhood birthday?" },

  // ════════════════════════════════════════
  // FAMILY (84 вопроса)
  // ════════════════════════════════════════
  { chapter: "family", ru: "Расскажите о традиции вашей семьи.", en: "Tell about a family tradition." },
  { chapter: "family", ru: "Какой урок вы получили от родителей?", en: "What lesson did you learn from your parents?" },
  { chapter: "family", ru: "Какой семейный праздник запомнился больше всего?", en: "What family celebration was most memorable?" },
  { chapter: "family", ru: "Что вы хотели бы передать своим детям?", en: "What would you want to pass on to your children?" },
  { chapter: "family", ru: "Как познакомились ваши родители?", en: "How did your parents meet?" },
  { chapter: "family", ru: "Какой самый старый семейный рецепт вы знаете?", en: "What is the oldest family recipe you know?" },
  { chapter: "family", ru: "Какая семейная фотография дороже всего для вас?", en: "What family photo is most precious to you?" },
  { chapter: "family", ru: "Расскажите историю бабушки или дедушки.", en: "Tell a story about your grandmother or grandfather." },
  { chapter: "family", ru: "Какие слова мамы вы помните наизусть?", en: "What words of your mother do you know by heart?" },
  { chapter: "family", ru: "Чему вас научил отец?", en: "What did your father teach you?" },
  { chapter: "family", ru: "Какой семейный конфликт научил вас чему-то важному?", en: "What family conflict taught you something important?" },
  { chapter: "family", ru: "Как ваша семья переживала трудные времена?", en: "How did your family get through hard times?" },
  { chapter: "family", ru: "Какая черта характера передаётся в вашей семье?", en: "What character trait runs in your family?" },
  { chapter: "family", ru: "Что ваши родители делали лучше всего?", en: "What did your parents do best?" },
  { chapter: "family", ru: "Какой семейный секрет вы узнали, когда повзрослели?", en: "What family secret did you learn as an adult?" },
  { chapter: "family", ru: "Как проходили выходные в вашей семье?", en: "How did weekends go in your family?" },
  { chapter: "family", ru: "Какой момент сплотил вашу семью?", en: "What moment brought your family together?" },
  { chapter: "family", ru: "Какое семейное застолье вы помните ярче всего?", en: "What family feast do you remember most vividly?" },
  { chapter: "family", ru: "Расскажите о брате или сестре. Как сложились ваши отношения?", en: "Tell about a sibling. How did your relationship develop?" },
  { chapter: "family", ru: "Какую роль играла бабушка в вашей жизни?", en: "What role did your grandmother play in your life?" },
  { chapter: "family", ru: "Что бы вы хотели узнать о своих предках?", en: "What would you want to know about your ancestors?" },
  { chapter: "family", ru: "Какую семейную историю пересказывают из поколения в поколение?", en: "What family story is passed down through generations?" },
  { chapter: "family", ru: "Как отмечали дни рождения в вашей семье?", en: "How were birthdays celebrated in your family?" },
  { chapter: "family", ru: "Какие ценности объединяют вашу семью?", en: "What values unite your family?" },
  { chapter: "family", ru: "Кто в семье был самым мудрым?", en: "Who in the family was the wisest?" },
  { chapter: "family", ru: "Какой переезд или перемена повлияли на вашу семью?", en: "What move or change affected your family?" },
  { chapter: "family", ru: "Как в вашей семье выражали любовь?", en: "How did your family express love?" },
  { chapter: "family", ru: "Какой семейный ритуал вы сохраняете?", en: "What family ritual do you preserve?" },
  { chapter: "family", ru: "Расскажите о семейной реликвии.", en: "Tell about a family heirloom." },
  { chapter: "family", ru: "Какой момент разлуки с семьёй был самым тяжёлым?", en: "What moment of separation from family was hardest?" },
  { chapter: "family", ru: "Чему вы научились у старшего поколения?", en: "What did you learn from the older generation?" },
  { chapter: "family", ru: "Как ваша семья праздновала Новый год?", en: "How did your family celebrate New Year?" },
  { chapter: "family", ru: "Какой семейный анекдот вы рассказываете чаще всего?", en: "What family anecdote do you tell most often?" },
  { chapter: "family", ru: "Какой совет мамы или папы оказался самым верным?", en: "What parental advice turned out to be the truest?" },
  { chapter: "family", ru: "Откуда ваша фамилия? Знаете ли вы её историю?", en: "Where does your last name come from? Do you know its history?" },
  { chapter: "family", ru: "Какое поколение в вашей семье вас вдохновляет?", en: "What generation in your family inspires you?" },
  { chapter: "family", ru: "Как ваши родители справлялись с разногласиями?", en: "How did your parents handle disagreements?" },
  { chapter: "family", ru: "Какой подвиг совершил кто-то из вашей семьи?", en: "What heroic act did someone in your family do?" },
  { chapter: "family", ru: "Расскажите о родственнике, которым вы гордитесь.", en: "Tell about a relative you're proud of." },
  { chapter: "family", ru: "Какие песни пели в вашей семье?", en: "What songs were sung in your family?" },
  { chapter: "family", ru: "Как изменилась ваша семья за вашу жизнь?", en: "How has your family changed during your lifetime?" },
  { chapter: "family", ru: "Какой момент воссоединения с семьёй вы помните?", en: "What family reunion moment do you remember?" },
  { chapter: "family", ru: "Какую семейную ошибку вы не хотите повторять?", en: "What family mistake do you not want to repeat?" },
  { chapter: "family", ru: "Кто в семье лучше всех рассказывал истории?", en: "Who in the family was the best storyteller?" },
  { chapter: "family", ru: "Какой родственник повлиял на ваш выбор профессии?", en: "What relative influenced your career choice?" },
  { chapter: "family", ru: "Как ваша семья относилась к религии или вере?", en: "How did your family relate to religion or faith?" },
  { chapter: "family", ru: "Какую потерю в семье вы переживали тяжелее всего?", en: "What family loss was hardest for you?" },
  { chapter: "family", ru: "Что объединяет вас с вашими родителями?", en: "What connects you to your parents?" },
  { chapter: "family", ru: "Какое семейное путешествие вы помните?", en: "What family trip do you remember?" },
  { chapter: "family", ru: "Расскажите о дяде, тёте или другом родственнике.", en: "Tell about an uncle, aunt, or other relative." },
  { chapter: "family", ru: "Какую роль играла еда в вашей семье?", en: "What role did food play in your family?" },
  { chapter: "family", ru: "Как ваши предки оказались там, где вы выросли?", en: "How did your ancestors end up where you grew up?" },
  { chapter: "family", ru: "Какие привычки вы унаследовали от родителей?", en: "What habits did you inherit from your parents?" },
  { chapter: "family", ru: "Какой момент гордости за семью вы пережили?", en: "What moment of family pride did you experience?" },
  { chapter: "family", ru: "Как ваша семья поддерживала вас в трудные моменты?", en: "How did your family support you in hard times?" },
  { chapter: "family", ru: "Какое семейное правило казалось странным, но оказалось мудрым?", en: "What family rule seemed strange but turned out wise?" },
  { chapter: "family", ru: "Как ваша семья относилась к образованию?", en: "How did your family feel about education?" },
  { chapter: "family", ru: "Кто из предков прожил самую необычную жизнь?", en: "Which ancestor lived the most unusual life?" },
  { chapter: "family", ru: "Какие вещи из родительского дома вы храните?", en: "What items from your parents' home do you keep?" },
  { chapter: "family", ru: "Как звали ваших прабабушек и прадедушек?", en: "What were your great-grandparents' names?" },
  { chapter: "family", ru: "Какой семейный обычай вы хотите сохранить навсегда?", en: "What family custom do you want to preserve forever?" },
  { chapter: "family", ru: "Расскажите о самом сильном человеке в вашей семье.", en: "Tell about the strongest person in your family." },
  { chapter: "family", ru: "Как ваша семья справлялась с бедностью или нуждой?", en: "How did your family cope with poverty or need?" },
  { chapter: "family", ru: "Какие национальные или культурные традиции есть в вашей семье?", en: "What national or cultural traditions exist in your family?" },
  { chapter: "family", ru: "Что вы унаследовали от мамы? А от папы?", en: "What did you inherit from your mother? And from your father?" },
  { chapter: "family", ru: "Какой семейный ужин вы помните в деталях?", en: "What family dinner do you remember in detail?" },
  { chapter: "family", ru: "Расскажите о любви в вашей семье.", en: "Tell about love in your family." },
  { chapter: "family", ru: "Какой родственник был самым весёлым?", en: "Which relative was the funniest?" },
  { chapter: "family", ru: "Как ваша семья относилась к деньгам?", en: "How did your family feel about money?" },
  { chapter: "family", ru: "Какое семейное фото рассказывает больше всего?", en: "What family photo tells the most?" },
  { chapter: "family", ru: "Какой пример ваших родителей вы несёте через жизнь?", en: "What example of your parents do you carry through life?" },
  { chapter: "family", ru: "Что бы вы спросили у своих предков, если бы могли?", en: "What would you ask your ancestors if you could?" },
  { chapter: "family", ru: "Какой семейный кризис сделал вас сильнее?", en: "What family crisis made you stronger?" },
  { chapter: "family", ru: "Какое наследство — не материальное — вам оставила семья?", en: "What non-material inheritance did your family leave you?" },
  { chapter: "family", ru: "Расскажите о домашнем животном, которое было частью семьи.", en: "Tell about a pet that was part of the family." },
  { chapter: "family", ru: "Какой момент вы хотите, чтобы ваши потомки знали о вашей семье?", en: "What moment do you want your descendants to know about your family?" },

  // ════════════════════════════════════════
  // RELATIONSHIPS (84 вопроса)
  // ════════════════════════════════════════
  { chapter: "relationships", ru: "Какой разговор изменил вашу жизнь?", en: "What conversation changed your life?" },
  { chapter: "relationships", ru: "Кто ваш самый близкий друг и почему?", en: "Who is your closest friend and why?" },
  { chapter: "relationships", ru: "Какой совет по отношениям вы бы дали молодым?", en: "What relationship advice would you give to young people?" },
  { chapter: "relationships", ru: "Расскажите о встрече, которая изменила вашу судьбу.", en: "Tell about a meeting that changed your destiny." },
  { chapter: "relationships", ru: "Как вы встретили свою любовь?", en: "How did you meet your love?" },
  { chapter: "relationships", ru: "Какой поступок друга вы никогда не забудете?", en: "What act of a friend will you never forget?" },
  { chapter: "relationships", ru: "Кто научил вас прощать?", en: "Who taught you to forgive?" },
  { chapter: "relationships", ru: "Какое расставание далось вам тяжелее всего?", en: "What breakup was hardest for you?" },
  { chapter: "relationships", ru: "Что значит для вас настоящая дружба?", en: "What does true friendship mean to you?" },
  { chapter: "relationships", ru: "Какую ошибку в отношениях вы больше не повторите?", en: "What relationship mistake will you never repeat?" },
  { chapter: "relationships", ru: "Как вы поняли, что нашли своего человека?", en: "How did you know you found your person?" },
  { chapter: "relationships", ru: "Кто поддержал вас, когда все отвернулись?", en: "Who supported you when everyone turned away?" },
  { chapter: "relationships", ru: "Какой комплимент вы помните всю жизнь?", en: "What compliment do you remember your whole life?" },
  { chapter: "relationships", ru: "Что самое важное в браке или партнёрстве?", en: "What is most important in marriage or partnership?" },
  { chapter: "relationships", ru: "Расскажите о человеке, который изменил вашу точку зрения.", en: "Tell about a person who changed your perspective." },
  { chapter: "relationships", ru: "Какой момент близости вы помните ярче всего?", en: "What moment of closeness do you remember most vividly?" },
  { chapter: "relationships", ru: "Как вы переживали предательство?", en: "How did you handle betrayal?" },
  { chapter: "relationships", ru: "Кого вы считаете своим наставником?", en: "Who do you consider your mentor?" },
  { chapter: "relationships", ru: "Какое письмо или сообщение вы храните?", en: "What letter or message do you keep?" },
  { chapter: "relationships", ru: "Что вы поняли о людях с возрастом?", en: "What did you understand about people with age?" },
  { chapter: "relationships", ru: "Какой человек появился в вашей жизни в нужный момент?", en: "What person appeared in your life at the right moment?" },
  { chapter: "relationships", ru: "Как вы научились доверять людям?", en: "How did you learn to trust people?" },
  { chapter: "relationships", ru: "Какой конфликт сделал ваши отношения крепче?", en: "What conflict made your relationship stronger?" },
  { chapter: "relationships", ru: "Расскажите о первой влюблённости.", en: "Tell about your first crush." },
  { chapter: "relationships", ru: "Что вы цените в людях больше всего?", en: "What do you value in people the most?" },
  { chapter: "relationships", ru: "Кому вы так и не сказали «спасибо»?", en: "Who did you never say 'thank you' to?" },
  { chapter: "relationships", ru: "Какой жест заботы тронул вас до глубины души?", en: "What caring gesture touched you deeply?" },
  { chapter: "relationships", ru: "Как вы находите общий язык с разными людьми?", en: "How do you find common ground with different people?" },
  { chapter: "relationships", ru: "Какой друг детства остался с вами?", en: "What childhood friend stayed with you?" },
  { chapter: "relationships", ru: "Что разрушает отношения быстрее всего?", en: "What destroys relationships the fastest?" },
  { chapter: "relationships", ru: "Какой момент примирения вы помните?", en: "What moment of reconciliation do you remember?" },
  { chapter: "relationships", ru: "Кто вас понимает лучше всех?", en: "Who understands you best?" },
  { chapter: "relationships", ru: "Какой подарок от близкого человека вы цените?", en: "What gift from a loved one do you treasure?" },
  { chapter: "relationships", ru: "Как вы познакомились с лучшим другом?", en: "How did you meet your best friend?" },
  { chapter: "relationships", ru: "Какой совет вам дал друг, который оказался верным?", en: "What friend's advice turned out to be right?" },
  { chapter: "relationships", ru: "Расскажите о человеке, который верил в вас.", en: "Tell about a person who believed in you." },
  { chapter: "relationships", ru: "Какой урок вы получили от любви?", en: "What lesson did you learn from love?" },
  { chapter: "relationships", ru: "Что бы вы хотели сказать человеку, которого уже нет?", en: "What would you want to say to someone who is no longer here?" },
  { chapter: "relationships", ru: "Какая случайная встреча стала судьбоносной?", en: "What chance encounter became fateful?" },
  { chapter: "relationships", ru: "Как вы выражаете любовь?", en: "How do you express love?" },
  { chapter: "relationships", ru: "Кто заставил вас поверить в себя?", en: "Who made you believe in yourself?" },
  { chapter: "relationships", ru: "Какой момент показал вам, кто ваш настоящий друг?", en: "What moment showed you who your true friend was?" },
  { chapter: "relationships", ru: "Как вы научились отпускать людей?", en: "How did you learn to let people go?" },
  { chapter: "relationships", ru: "Что вы поняли о себе через отношения с другими?", en: "What did you learn about yourself through relationships?" },
  { chapter: "relationships", ru: "Какой человек изменил ваше представление о добре?", en: "What person changed your idea of goodness?" },
  { chapter: "relationships", ru: "Расскажите о свадьбе — своей или близкого человека.", en: "Tell about a wedding — yours or a loved one's." },
  { chapter: "relationships", ru: "Какой момент научил вас ценить людей рядом?", en: "What moment taught you to value the people around you?" },
  { chapter: "relationships", ru: "Как вы помирились с человеком после долгой ссоры?", en: "How did you make up with someone after a long argument?" },
  { chapter: "relationships", ru: "Кого вы потеряли и кого нашли?", en: "Who did you lose and who did you find?" },
  { chapter: "relationships", ru: "Какой жизненный этап изменил ваши отношения с людьми?", en: "What life stage changed your relationships with people?" },
  { chapter: "relationships", ru: "Что значит для вас верность?", en: "What does loyalty mean to you?" },
  { chapter: "relationships", ru: "Какой незнакомец сделал вам добро?", en: "What stranger did you a kindness?" },
  { chapter: "relationships", ru: "Как вы научились говорить «нет»?", en: "How did you learn to say 'no'?" },
  { chapter: "relationships", ru: "Какой момент с партнёром вы хотите запомнить навсегда?", en: "What moment with your partner do you want to remember forever?" },
  { chapter: "relationships", ru: "Расскажите о дружбе, которая пережила расстояние.", en: "Tell about a friendship that survived distance." },
  { chapter: "relationships", ru: "Какой человек научил вас быть лучше?", en: "What person taught you to be better?" },
  { chapter: "relationships", ru: "Что для вас значит одиночество?", en: "What does loneliness mean to you?" },
  { chapter: "relationships", ru: "Какой самый красивый поступок совершил для вас кто-то?", en: "What is the most beautiful thing someone did for you?" },
  { chapter: "relationships", ru: "Как вы поддерживаете отношения на расстоянии?", en: "How do you maintain long-distance relationships?" },
  { chapter: "relationships", ru: "Кому вы доверяете свои секреты?", en: "Who do you trust with your secrets?" },
  { chapter: "relationships", ru: "Какой момент показал вам силу любви?", en: "What moment showed you the power of love?" },
  { chapter: "relationships", ru: "Расскажите о встрече, которую вы ждали очень долго.", en: "Tell about a reunion you waited for a very long time." },
  { chapter: "relationships", ru: "Какой человек научил вас терпению?", en: "What person taught you patience?" },
  { chapter: "relationships", ru: "Что бы вы написали в письме своему лучшему другу?", en: "What would you write in a letter to your best friend?" },

  // ════════════════════════════════════════
  // CAREER (84 вопроса)
  // ════════════════════════════════════════
  { chapter: "career", ru: "Чем вы занимаетесь и почему выбрали эту профессию?", en: "What do you do and why did you choose this profession?" },
  { chapter: "career", ru: "Какое достижение в работе вы считаете главным?", en: "What work achievement do you consider most important?" },
  { chapter: "career", ru: "Какой урок вы получили на работе?", en: "What lesson did you learn at work?" },
  { chapter: "career", ru: "Если бы вы начали карьеру заново, что бы изменили?", en: "If you could restart your career, what would you change?" },
  { chapter: "career", ru: "Кто был вашим лучшим начальником и почему?", en: "Who was your best boss and why?" },
  { chapter: "career", ru: "Какой рабочий день вы не забудете?", en: "What work day will you never forget?" },
  { chapter: "career", ru: "Какая ошибка на работе стала уроком?", en: "What work mistake became a lesson?" },
  { chapter: "career", ru: "Расскажите о своём первом рабочем дне.", en: "Tell about your first day at work." },
  { chapter: "career", ru: "Какой проект дал вам больше всего опыта?", en: "What project gave you the most experience?" },
  { chapter: "career", ru: "Что вас мотивирует работать?", en: "What motivates you to work?" },
  { chapter: "career", ru: "Какой навык оказался самым полезным?", en: "What skill turned out to be the most useful?" },
  { chapter: "career", ru: "Как вы справлялись с неудачами на работе?", en: "How did you handle failures at work?" },
  { chapter: "career", ru: "Какой коллега повлиял на вашу карьеру?", en: "What colleague influenced your career?" },
  { chapter: "career", ru: "Что бы вы посоветовали начинающему специалисту?", en: "What advice would you give a beginner?" },
  { chapter: "career", ru: "Какой момент на работе дал вам чувство гордости?", en: "What work moment gave you a sense of pride?" },
  { chapter: "career", ru: "Как вы совмещали работу и личную жизнь?", en: "How did you balance work and personal life?" },
  { chapter: "career", ru: "Какую самую сложную задачу вы решили?", en: "What was the hardest problem you solved?" },
  { chapter: "career", ru: "Какая работа была вашей первой?", en: "What was your first job?" },
  { chapter: "career", ru: "Что изменилось в вашей профессии за вашу жизнь?", en: "What has changed in your profession during your lifetime?" },
  { chapter: "career", ru: "Какой совет руководителя вы помните?", en: "What advice from a boss do you remember?" },
  { chapter: "career", ru: "Были ли моменты, когда вы хотели всё бросить?", en: "Were there moments when you wanted to quit everything?" },
  { chapter: "career", ru: "Какой человек помог вам в карьере?", en: "What person helped you in your career?" },
  { chapter: "career", ru: "Что вы создали, чем гордитесь?", en: "What did you create that you're proud of?" },
  { chapter: "career", ru: "Как вы находили работу в трудные времена?", en: "How did you find work in hard times?" },
  { chapter: "career", ru: "Какой рабочий ритуал у вас есть?", en: "What work ritual do you have?" },
  { chapter: "career", ru: "Что самое ценное в вашей профессии?", en: "What is most valuable in your profession?" },
  { chapter: "career", ru: "Расскажите о самом необычном проекте.", en: "Tell about the most unusual project." },
  { chapter: "career", ru: "Какой навык вы освоили самостоятельно?", en: "What skill did you learn on your own?" },
  { chapter: "career", ru: "Как технологии изменили вашу работу?", en: "How did technology change your work?" },
  { chapter: "career", ru: "Какой рабочий кризис вы преодолели?", en: "What work crisis did you overcome?" },
  { chapter: "career", ru: "Что бы вы делали, если бы деньги не имели значения?", en: "What would you do if money didn't matter?" },
  { chapter: "career", ru: "Какие качества нужны для успеха в вашей профессии?", en: "What qualities are needed for success in your profession?" },
  { chapter: "career", ru: "Расскажите о команде, с которой вы работали.", en: "Tell about a team you worked with." },
  { chapter: "career", ru: "Какой момент карьеры стал переломным?", en: "What career moment was a turning point?" },
  { chapter: "career", ru: "Чем отличается ваша профессия от того, что вы о ней думали?", en: "How does your profession differ from what you imagined?" },
  { chapter: "career", ru: "Какую профессию вы хотели бы попробовать?", en: "What profession would you like to try?" },
  { chapter: "career", ru: "Какой был самый тяжёлый период на работе?", en: "What was the hardest period at work?" },
  { chapter: "career", ru: "Что вас научила работа о жизни?", en: "What did work teach you about life?" },
  { chapter: "career", ru: "Какой случай на работе рассмешил вас?", en: "What incident at work made you laugh?" },
  { chapter: "career", ru: "Как вы принимали важные решения в карьере?", en: "How did you make important career decisions?" },
  { chapter: "career", ru: "Какой клиент или заказ вам запомнился?", en: "What client or order was memorable?" },
  { chapter: "career", ru: "Что даёт вам работа помимо денег?", en: "What does work give you besides money?" },
  { chapter: "career", ru: "Как вы учились чему-то новому на работе?", en: "How did you learn something new at work?" },
  { chapter: "career", ru: "Какой вклад в профессию вы считаете своим?", en: "What contribution to your profession do you consider yours?" },
  { chapter: "career", ru: "Расскажите о рабочем путешествии.", en: "Tell about a work trip." },
  { chapter: "career", ru: "Какую роль играет работа в вашей жизни сегодня?", en: "What role does work play in your life today?" },
  { chapter: "career", ru: "Какой профессиональный риск оправдал себя?", en: "What professional risk paid off?" },

  // ════════════════════════════════════════
  // DAILY LIFE (84 вопроса)
  // ════════════════════════════════════════
  { chapter: "daily_life", ru: "Что сегодня сделало вас счастливым?", en: "What made you happy today?" },
  { chapter: "daily_life", ru: "Какой момент дня запомнился больше всего?", en: "What moment stood out the most today?" },
  { chapter: "daily_life", ru: "Что заставило вас улыбнуться сегодня?", en: "What made you smile today?" },
  { chapter: "daily_life", ru: "Какой маленький поступок принёс вам радость?", en: "What small act brought you joy?" },
  { chapter: "daily_life", ru: "Как выглядит ваше идеальное утро?", en: "What does your ideal morning look like?" },
  { chapter: "daily_life", ru: "Какой ваш любимый ритуал дня?", en: "What is your favorite daily ritual?" },
  { chapter: "daily_life", ru: "Что вы готовили на ужин?", en: "What did you cook for dinner?" },
  { chapter: "daily_life", ru: "Какое место в вашем городе вы любите?", en: "What place in your city do you love?" },
  { chapter: "daily_life", ru: "Что вы делаете для отдыха?", en: "What do you do to relax?" },
  { chapter: "daily_life", ru: "Какую музыку вы слушаете каждый день?", en: "What music do you listen to every day?" },
  { chapter: "daily_life", ru: "Как вы проводите вечера?", en: "How do you spend your evenings?" },
  { chapter: "daily_life", ru: "Что вы видите из окна?", en: "What do you see from your window?" },
  { chapter: "daily_life", ru: "Какой ваш любимый способ передвижения?", en: "What is your favorite way to get around?" },
  { chapter: "daily_life", ru: "Что вы делаете, когда не можете уснуть?", en: "What do you do when you can't sleep?" },
  { chapter: "daily_life", ru: "Какой обычный день вы считаете идеальным?", en: "What ordinary day do you consider ideal?" },
  { chapter: "daily_life", ru: "Что вы обычно берёте с собой, выходя из дома?", en: "What do you usually take with you when leaving home?" },
  { chapter: "daily_life", ru: "Как вы начинаете свой день?", en: "How do you start your day?" },
  { chapter: "daily_life", ru: "Какой ваш любимый напиток?", en: "What is your favorite drink?" },
  { chapter: "daily_life", ru: "Что вы читаете сейчас?", en: "What are you reading right now?" },
  { chapter: "daily_life", ru: "Какой запах ассоциируется с вашим домом?", en: "What smell do you associate with your home?" },
  { chapter: "daily_life", ru: "Как выглядит ваше любимое место в доме?", en: "What does your favorite spot in the house look like?" },
  { chapter: "daily_life", ru: "Что вы делаете по воскресеньям?", en: "What do you do on Sundays?" },
  { chapter: "daily_life", ru: "Какая мелочь улучшает ваш день?", en: "What little thing improves your day?" },
  { chapter: "daily_life", ru: "Какое блюдо вы готовите лучше всего?", en: "What dish do you cook best?" },
  { chapter: "daily_life", ru: "Какой маршрут вы проходите каждый день?", en: "What route do you walk every day?" },
  { chapter: "daily_life", ru: "Что вы смотрите по телевизору или в интернете?", en: "What do you watch on TV or online?" },
  { chapter: "daily_life", ru: "Как вы отдыхаете после тяжёлого дня?", en: "How do you rest after a hard day?" },
  { chapter: "daily_life", ru: "Какая вещь в вашем доме вам дороже всего?", en: "What item in your home is most precious to you?" },
  { chapter: "daily_life", ru: "Что вы делаете утром перед выходом?", en: "What do you do in the morning before leaving?" },
  { chapter: "daily_life", ru: "Какой ваш любимый сезон и почему?", en: "What is your favorite season and why?" },
  { chapter: "daily_life", ru: "Как вы проводите обеденный перерыв?", en: "How do you spend your lunch break?" },
  { chapter: "daily_life", ru: "Какие звуки окружают вас каждый день?", en: "What sounds surround you every day?" },
  { chapter: "daily_life", ru: "Что вас раздражает в повседневной жизни?", en: "What annoys you in daily life?" },
  { chapter: "daily_life", ru: "Какая прогулка запомнилась вам?", en: "What walk was memorable for you?" },
  { chapter: "daily_life", ru: "Как вы ухаживаете за собой?", en: "How do you take care of yourself?" },
  { chapter: "daily_life", ru: "Какой ваш любимый магазин или рынок?", en: "What is your favorite shop or market?" },
  { chapter: "daily_life", ru: "Что вы делаете в очереди или пробке?", en: "What do you do in line or in traffic?" },
  { chapter: "daily_life", ru: "Какой погодный день вы любите больше всего?", en: "What kind of weather day do you love most?" },
  { chapter: "daily_life", ru: "Как выглядит ваш рабочий стол?", en: "What does your desk look like?" },
  { chapter: "daily_life", ru: "Какие привычки появились у вас с возрастом?", en: "What habits developed with age?" },
  { chapter: "daily_life", ru: "Что вы делаете, чтобы сохранить здоровье?", en: "What do you do to stay healthy?" },
  { chapter: "daily_life", ru: "Какой ваш любимый способ провести выходной?", en: "What is your favorite way to spend a day off?" },

  // ════════════════════════════════════════
  // TRAVEL (84 вопроса)
  // ════════════════════════════════════════
  { chapter: "travel", ru: "Какое место на Земле вы считаете своим?", en: "What place on Earth do you call your own?" },
  { chapter: "travel", ru: "Куда бы вы хотели вернуться снова?", en: "Where would you want to return to again?" },
  { chapter: "travel", ru: "Какое путешествие изменило ваш взгляд на мир?", en: "What journey changed your view of the world?" },
  { chapter: "travel", ru: "Опишите место, где вы чувствуете себя в безопасности.", en: "Describe a place where you feel safe." },
  { chapter: "travel", ru: "Какая страна удивила вас больше всего?", en: "What country surprised you the most?" },
  { chapter: "travel", ru: "Расскажите о самом длинном путешествии.", en: "Tell about the longest journey." },
  { chapter: "travel", ru: "Какой город произвёл на вас впечатление?", en: "What city impressed you?" },
  { chapter: "travel", ru: "Какой закат или рассвет вы помните?", en: "What sunset or sunrise do you remember?" },
  { chapter: "travel", ru: "Какое приключение в путешествии запомнилось?", en: "What travel adventure was memorable?" },
  { chapter: "travel", ru: "Где вы попробовали лучшую еду в жизни?", en: "Where did you try the best food of your life?" },
  { chapter: "travel", ru: "Какую культуру вы хотели бы узнать ближе?", en: "What culture would you like to know better?" },
  { chapter: "travel", ru: "Какой дорогой вы ехали и помните каждый поворот?", en: "What road did you drive and remember every turn?" },
  { chapter: "travel", ru: "Где вы почувствовали себя другим человеком?", en: "Where did you feel like a different person?" },
  { chapter: "travel", ru: "Какое море или озеро вы помните?", en: "What sea or lake do you remember?" },
  { chapter: "travel", ru: "Расскажите о встрече с местными жителями.", en: "Tell about meeting local people." },
  { chapter: "travel", ru: "Какой пейзаж вы хотели бы видеть каждый день?", en: "What landscape would you want to see every day?" },
  { chapter: "travel", ru: "Какое место показалось вам волшебным?", en: "What place seemed magical to you?" },
  { chapter: "travel", ru: "Какой музей или памятник вас впечатлил?", en: "What museum or monument impressed you?" },
  { chapter: "travel", ru: "Где вы ночевали под открытым небом?", en: "Where did you sleep under the open sky?" },
  { chapter: "travel", ru: "Какое путешествие было самым неожиданным?", en: "What trip was the most unexpected?" },
  { chapter: "travel", ru: "Какой аэропорт, вокзал или порт вы помните?", en: "What airport, station, or port do you remember?" },
  { chapter: "travel", ru: "Где вы хотели бы жить, если не здесь?", en: "Where would you want to live if not here?" },
  { chapter: "travel", ru: "Какая горная вершина или долина вас поразила?", en: "What mountain peak or valley amazed you?" },
  { chapter: "travel", ru: "Расскажите о попутчике, которого запомнили.", en: "Tell about a travel companion you remember." },
  { chapter: "travel", ru: "Какой рынок или базар вы посещали?", en: "What market or bazaar did you visit?" },
  { chapter: "travel", ru: "Где вы заблудились и что из этого вышло?", en: "Where did you get lost and what came of it?" },
  { chapter: "travel", ru: "Какой звук ассоциируется у вас с путешествием?", en: "What sound do you associate with travel?" },
  { chapter: "travel", ru: "Какую границу вы пересекли впервые?", en: "What border did you cross for the first time?" },
  { chapter: "travel", ru: "Какое место вы посетили мечтой и были разочарованы?", en: "What place did you dream of visiting but were disappointed by?" },
  { chapter: "travel", ru: "Где вы увидели звёзды ярче всего?", en: "Where did you see the stars brightest?" },
  { chapter: "travel", ru: "Какой сувенир вы привезли из путешествия?", en: "What souvenir did you bring from a trip?" },
  { chapter: "travel", ru: "Расскажите о путешествии с семьёй.", en: "Tell about a family trip." },
  { chapter: "travel", ru: "Какой вид транспорта вы запомнили — лодка, поезд, автобус?", en: "What mode of transport do you remember — boat, train, bus?" },
  { chapter: "travel", ru: "Где вы впервые увидели море?", en: "Where did you first see the sea?" },
  { chapter: "travel", ru: "Какое место на карте вы мечтаете посетить?", en: "What place on the map do you dream of visiting?" },
  { chapter: "travel", ru: "Какой храм, церковь или мечеть вы посетили?", en: "What temple, church, or mosque did you visit?" },
  { chapter: "travel", ru: "Расскажите о погоде в незабываемом путешествии.", en: "Tell about the weather on an unforgettable trip." },
  { chapter: "travel", ru: "Какой язык или обычай вы узнали в путешествии?", en: "What language or custom did you learn while traveling?" },
  { chapter: "travel", ru: "Где вы испытали культурный шок?", en: "Where did you experience culture shock?" },
  { chapter: "travel", ru: "Какой парк или сад вы помните?", en: "What park or garden do you remember?" },
  { chapter: "travel", ru: "Какое путешествие вы совершили в одиночку?", en: "What trip did you take alone?" },
  { chapter: "travel", ru: "Где вы были счастливее всего?", en: "Where were you happiest?" },

  // ════════════════════════════════════════
  // DREAMS (84 вопроса)
  // ════════════════════════════════════════
  { chapter: "dreams", ru: "О чём вы мечтали сегодня?", en: "What did you dream about today?" },
  { chapter: "dreams", ru: "Какая мечта у вас ещё не осуществилась?", en: "What dream hasn't come true yet?" },
  { chapter: "dreams", ru: "Что бы вы сделали, если бы не было ограничений?", en: "What would you do if there were no limitations?" },
  { chapter: "dreams", ru: "Какой вы представляете свою жизнь через 10 лет?", en: "How do you imagine your life in 10 years?" },
  { chapter: "dreams", ru: "Какая мечта детства сбылась?", en: "What childhood dream came true?" },
  { chapter: "dreams", ru: "Что бы вы хотели изобрести?", en: "What would you want to invent?" },
  { chapter: "dreams", ru: "Какой дом вы мечтаете построить?", en: "What house do you dream of building?" },
  { chapter: "dreams", ru: "Если бы вы могли прожить другую жизнь — какую?", en: "If you could live another life — what would it be?" },
  { chapter: "dreams", ru: "Какое умение вы хотели бы освоить?", en: "What skill would you want to master?" },
  { chapter: "dreams", ru: "О какой стране вы мечтаете?", en: "What country do you dream about?" },
  { chapter: "dreams", ru: "Какой проект вы хотели бы начать?", en: "What project would you want to start?" },
  { chapter: "dreams", ru: "Если бы вы написали книгу — о чём она была бы?", en: "If you wrote a book — what would it be about?" },
  { chapter: "dreams", ru: "Какое событие вы хотели бы увидеть в будущем?", en: "What event would you want to see in the future?" },
  { chapter: "dreams", ru: "Кем бы вы хотели стать в параллельной вселенной?", en: "Who would you want to be in a parallel universe?" },
  { chapter: "dreams", ru: "Что бы вы изменили в мире?", en: "What would you change in the world?" },
  { chapter: "dreams", ru: "Какой талант вы хотели бы иметь?", en: "What talent would you want to have?" },
  { chapter: "dreams", ru: "Какую цель вы хотите достичь до конца жизни?", en: "What goal do you want to achieve in your lifetime?" },
  { chapter: "dreams", ru: "Если бы время не было ограничено — что бы вы делали?", en: "If time were unlimited — what would you do?" },
  { chapter: "dreams", ru: "Какой подвиг вы хотели бы совершить?", en: "What heroic act would you want to do?" },
  { chapter: "dreams", ru: "Какой навык вы хотите передать потомкам?", en: "What skill do you want to pass to descendants?" },
  { chapter: "dreams", ru: "О чём вы мечтали в 20 лет?", en: "What did you dream about at 20?" },
  { chapter: "dreams", ru: "Какая мечта казалась невозможной, но стала реальностью?", en: "What dream seemed impossible but became reality?" },
  { chapter: "dreams", ru: "Что бы вы построили, если бы имели неограниченные ресурсы?", en: "What would you build with unlimited resources?" },
  { chapter: "dreams", ru: "Какой сон повторяется у вас снова и снова?", en: "What dream recurs again and again?" },
  { chapter: "dreams", ru: "Куда бы вы полетели, если бы могли полететь куда угодно?", en: "Where would you fly if you could fly anywhere?" },
  { chapter: "dreams", ru: "Какую эпоху вы хотели бы посетить?", en: "What era would you want to visit?" },
  { chapter: "dreams", ru: "Какой бизнес или проект вы мечтали создать?", en: "What business or project did you dream of creating?" },
  { chapter: "dreams", ru: "Что бы вы сделали в первый день на пенсии?", en: "What would you do on your first day of retirement?" },
  { chapter: "dreams", ru: "Какую суперспособность вы бы выбрали?", en: "What superpower would you choose?" },
  { chapter: "dreams", ru: "Какое приключение вы хотите пережить?", en: "What adventure do you want to experience?" },
  { chapter: "dreams", ru: "Какое наследие вы хотите оставить?", en: "What legacy do you want to leave?" },
  { chapter: "dreams", ru: "Какой концерт или событие вы мечтаете посетить?", en: "What concert or event do you dream of attending?" },
  { chapter: "dreams", ru: "Если бы вы могли поговорить с любым человеком — с кем?", en: "If you could talk to anyone — who?" },
  { chapter: "dreams", ru: "Какой мир вы хотели бы создать для потомков?", en: "What world would you want to create for descendants?" },
  { chapter: "dreams", ru: "Что бы вы хотели успеть сделать?", en: "What would you want to have time to do?" },
  { chapter: "dreams", ru: "Какой фильм о вашей жизни вы бы сняли?", en: "What movie about your life would you make?" },
  { chapter: "dreams", ru: "Какая мечта ещё греет ваше сердце?", en: "What dream still warms your heart?" },

  // ════════════════════════════════════════
  // VALUES (84 вопроса)
  // ════════════════════════════════════════
  { chapter: "values", ru: "Что для вас важнее всего в жизни?", en: "What is most important to you in life?" },
  { chapter: "values", ru: "Какой принцип вы никогда не нарушите?", en: "What principle would you never break?" },
  { chapter: "values", ru: "Что бы вы хотели рассказать своим внукам?", en: "What would you want to tell your grandchildren?" },
  { chapter: "values", ru: "Какая ценность досталась вам от предков?", en: "What value was passed down from your ancestors?" },
  { chapter: "values", ru: "Что для вас значит честность?", en: "What does honesty mean to you?" },
  { chapter: "values", ru: "Какой нравственный выбор вы делали?", en: "What moral choice have you made?" },
  { chapter: "values", ru: "Что значит для вас справедливость?", en: "What does justice mean to you?" },
  { chapter: "values", ru: "Какие правила вы установили для себя?", en: "What rules have you set for yourself?" },
  { chapter: "values", ru: "Что бы вы хотели, чтобы о вас помнили?", en: "What would you want to be remembered for?" },
  { chapter: "values", ru: "Какую ценность вы хотите привить детям?", en: "What value do you want to instill in your children?" },
  { chapter: "values", ru: "Что для вас значит свобода?", en: "What does freedom mean to you?" },
  { chapter: "values", ru: "Какой поступок вы считаете самым честным?", en: "What act do you consider the most honest?" },
  { chapter: "values", ru: "Что важнее — быть правым или быть добрым?", en: "What's more important — being right or being kind?" },
  { chapter: "values", ru: "Какой закон или правило вы бы изменили?", en: "What law or rule would you change?" },
  { chapter: "values", ru: "Что значит для вас ответственность?", en: "What does responsibility mean to you?" },
  { chapter: "values", ru: "Какой моральный компромисс вы не готовы на?", en: "What moral compromise are you not willing to make?" },
  { chapter: "values", ru: "Что для вас значит уважение?", en: "What does respect mean to you?" },
  { chapter: "values", ru: "Какая несправедливость задела вас глубже всего?", en: "What injustice hurt you the deepest?" },
  { chapter: "values", ru: "Что значит для вас семья — как ценность?", en: "What does family mean to you — as a value?" },
  { chapter: "values", ru: "Какой принцип помогает вам принимать решения?", en: "What principle helps you make decisions?" },
  { chapter: "values", ru: "Что для вас важнее — деньги или время?", en: "What is more important — money or time?" },
  { chapter: "values", ru: "Какую черту характера вы цените выше всего?", en: "What character trait do you value the most?" },
  { chapter: "values", ru: "Что значит для вас верность слову?", en: "What does keeping your word mean to you?" },
  { chapter: "values", ru: "Какой поступок вы считаете храбрым?", en: "What act do you consider brave?" },
  { chapter: "values", ru: "Что для вас значит доброта?", en: "What does kindness mean to you?" },
  { chapter: "values", ru: "Какая ценность помогла вам в трудный момент?", en: "What value helped you in a difficult moment?" },
  { chapter: "values", ru: "Что значит быть хорошим человеком?", en: "What does it mean to be a good person?" },
  { chapter: "values", ru: "Какой стандарт вы установили для своей жизни?", en: "What standard have you set for your life?" },
  { chapter: "values", ru: "Что для вас значит совесть?", en: "What does conscience mean to you?" },
  { chapter: "values", ru: "Какую роль играет вера в вашей жизни?", en: "What role does faith play in your life?" },
  { chapter: "values", ru: "Что для вас значит щедрость?", en: "What does generosity mean to you?" },
  { chapter: "values", ru: "Какой пример нравственности вы видели в жизни?", en: "What example of morality have you seen in life?" },
  { chapter: "values", ru: "Что бы вы защищали любой ценой?", en: "What would you defend at any cost?" },
  { chapter: "values", ru: "Какой урок морали вы получили?", en: "What moral lesson did you learn?" },
  { chapter: "values", ru: "Что для вас важнее — комфорт или принципы?", en: "What matters more — comfort or principles?" },
  { chapter: "values", ru: "Какое правило жизни вы хотите оставить потомкам?", en: "What life rule do you want to leave for descendants?" },

  // ════════════════════════════════════════
  // GRATITUDE (84 вопроса)
  // ════════════════════════════════════════
  { chapter: "gratitude", ru: "За что вы благодарны сегодня?", en: "What are you grateful for today?" },
  { chapter: "gratitude", ru: "Кому бы вы хотели сказать спасибо?", en: "Who would you like to thank?" },
  { chapter: "gratitude", ru: "Какой подарок судьбы вы цените больше всего?", en: "What gift of fate do you appreciate most?" },
  { chapter: "gratitude", ru: "Что хорошее произошло с вами на этой неделе?", en: "What good thing happened to you this week?" },
  { chapter: "gratitude", ru: "За какую возможность вы благодарны?", en: "What opportunity are you grateful for?" },
  { chapter: "gratitude", ru: "Какой человек сделал вашу жизнь лучше?", en: "What person made your life better?" },
  { chapter: "gratitude", ru: "За какой опыт вы благодарны, даже если он был тяжёлым?", en: "What experience are you grateful for, even though it was hard?" },
  { chapter: "gratitude", ru: "Какой момент счастья вы хотите запомнить?", en: "What moment of happiness do you want to remember?" },
  { chapter: "gratitude", ru: "Что вы принимаете как должное, но это — подарок?", en: "What do you take for granted but it's a gift?" },
  { chapter: "gratitude", ru: "За какой урок жизни вы благодарны?", en: "What life lesson are you grateful for?" },
  { chapter: "gratitude", ru: "Какое место наполняет вас благодарностью?", en: "What place fills you with gratitude?" },
  { chapter: "gratitude", ru: "За что вы благодарны своему телу?", en: "What are you grateful to your body for?" },
  { chapter: "gratitude", ru: "Какой простой момент вы цените?", en: "What simple moment do you treasure?" },
  { chapter: "gratitude", ru: "За какую дружбу вы благодарны?", en: "What friendship are you grateful for?" },
  { chapter: "gratitude", ru: "Что хорошее принёс вам этот год?", en: "What good did this year bring you?" },
  { chapter: "gratitude", ru: "За какую ошибку вы благодарны?", en: "What mistake are you grateful for?" },
  { chapter: "gratitude", ru: "Какая мелочь делает вашу жизнь приятнее?", en: "What little thing makes your life nicer?" },
  { chapter: "gratitude", ru: "За какую встречу вы благодарны судьбе?", en: "What encounter are you grateful to fate for?" },
  { chapter: "gratitude", ru: "Что хорошее есть в вашей жизни прямо сейчас?", en: "What good is in your life right now?" },
  { chapter: "gratitude", ru: "За какой навык или талант вы благодарны?", en: "What skill or talent are you grateful for?" },
  { chapter: "gratitude", ru: "Какой день в этом месяце был лучшим?", en: "What day this month was the best?" },
  { chapter: "gratitude", ru: "За какое решение вы благодарны себе?", en: "What decision are you grateful to yourself for?" },
  { chapter: "gratitude", ru: "Что делает вашу жизнь богатой?", en: "What makes your life rich?" },
  { chapter: "gratitude", ru: "За какую случайность вы благодарны?", en: "What coincidence are you grateful for?" },
  { chapter: "gratitude", ru: "Какой утренний момент принёс вам радость?", en: "What morning moment brought you joy?" },
  { chapter: "gratitude", ru: "За какую книгу, фильм или песню вы благодарны?", en: "What book, movie, or song are you grateful for?" },
  { chapter: "gratitude", ru: "Что в вашей жизни вы бы не хотели менять?", en: "What in your life would you not want to change?" },
  { chapter: "gratitude", ru: "За какого учителя или наставника вы благодарны?", en: "What teacher or mentor are you grateful for?" },
  { chapter: "gratitude", ru: "Какой природный момент наполнил вас благодарностью?", en: "What moment in nature filled you with gratitude?" },
  { chapter: "gratitude", ru: "За что вы благодарны своей семье?", en: "What are you grateful to your family for?" },
  { chapter: "gratitude", ru: "Какой неожиданный подарок вы получили?", en: "What unexpected gift did you receive?" },
  { chapter: "gratitude", ru: "За какой обычный день вы благодарны?", en: "What ordinary day are you grateful for?" },
  { chapter: "gratitude", ru: "Что хорошее дал вам этот город?", en: "What good did this city give you?" },
  { chapter: "gratitude", ru: "За какую возможность учиться вы благодарны?", en: "What learning opportunity are you grateful for?" },
  { chapter: "gratitude", ru: "Какой акт доброты вы получили от незнакомца?", en: "What act of kindness did you receive from a stranger?" },
  { chapter: "gratitude", ru: "За что вы благодарны этому моменту?", en: "What are you grateful for in this moment?" },

  // ════════════════════════════════════════
  // WISDOM (84 вопроса)
  // ════════════════════════════════════════
  { chapter: "wisdom", ru: "Что нового вы узнали сегодня?", en: "What new thing did you learn today?" },
  { chapter: "wisdom", ru: "Какой жизненный урок дался вам труднее всего?", en: "What life lesson was hardest for you?" },
  { chapter: "wisdom", ru: "Что бы вы посоветовали себе 20-летнему?", en: "What advice would you give your 20-year-old self?" },
  { chapter: "wisdom", ru: "Какая ошибка научила вас больше всего?", en: "What mistake taught you the most?" },
  { chapter: "wisdom", ru: "Какая фраза изменила ваше мышление?", en: "What phrase changed your thinking?" },
  { chapter: "wisdom", ru: "Что вы поняли о жизни только с возрастом?", en: "What did you understand about life only with age?" },
  { chapter: "wisdom", ru: "Какой совет вы бы дали своим детям?", en: "What advice would you give your children?" },
  { chapter: "wisdom", ru: "Какая книга повлияла на ваше мировоззрение?", en: "What book influenced your worldview?" },
  { chapter: "wisdom", ru: "Что вы знаете сейчас, чего не знали 10 лет назад?", en: "What do you know now that you didn't 10 years ago?" },
  { chapter: "wisdom", ru: "Какой человек научил вас мудрости?", en: "What person taught you wisdom?" },
  { chapter: "wisdom", ru: "Что значит жить хорошо?", en: "What does it mean to live well?" },
  { chapter: "wisdom", ru: "Какой провал стал вашим лучшим учителем?", en: "What failure was your best teacher?" },
  { chapter: "wisdom", ru: "Что бы вы сказали молодому поколению?", en: "What would you say to the younger generation?" },
  { chapter: "wisdom", ru: "Какой принцип помогает вам в трудные дни?", en: "What principle helps you on hard days?" },
  { chapter: "wisdom", ru: "Что вы узнали о себе в последние годы?", en: "What have you learned about yourself in recent years?" },
  { chapter: "wisdom", ru: "Какой опыт сделал вас мудрее?", en: "What experience made you wiser?" },
  { chapter: "wisdom", ru: "Что важнее — знания или опыт?", en: "What's more important — knowledge or experience?" },
  { chapter: "wisdom", ru: "Какой совет вы получили, но поняли его только спустя годы?", en: "What advice did you receive but only understood years later?" },
  { chapter: "wisdom", ru: "Что вы хотели бы знать раньше?", en: "What do you wish you had known earlier?" },
  { chapter: "wisdom", ru: "Какой урок терпения вы получили?", en: "What lesson in patience did you learn?" },
  { chapter: "wisdom", ru: "Что значит быть сильным?", en: "What does it mean to be strong?" },
  { chapter: "wisdom", ru: "Какая истина открылась вам через боль?", en: "What truth was revealed to you through pain?" },
  { chapter: "wisdom", ru: "Что вы поняли о деньгах?", en: "What did you learn about money?" },
  { chapter: "wisdom", ru: "Какой навык жизни вы считаете главным?", en: "What life skill do you consider the most important?" },
  { chapter: "wisdom", ru: "Что значит для вас успех?", en: "What does success mean to you?" },
  { chapter: "wisdom", ru: "Какой момент научил вас смирению?", en: "What moment taught you humility?" },
  { chapter: "wisdom", ru: "Что бы вы посоветовали себе перед важным решением?", en: "What would you advise yourself before an important decision?" },
  { chapter: "wisdom", ru: "Какая правда о жизни стала для вас откровением?", en: "What truth about life was a revelation to you?" },
  { chapter: "wisdom", ru: "Что вы узнали о счастье?", en: "What did you learn about happiness?" },
  { chapter: "wisdom", ru: "Какой жизненный цикл вы наблюдали?", en: "What life cycle have you observed?" },
  { chapter: "wisdom", ru: "Что значит жить без сожалений?", en: "What does it mean to live without regrets?" },
  { chapter: "wisdom", ru: "Какой урок преподнесла вам природа?", en: "What lesson did nature teach you?" },
  { chapter: "wisdom", ru: "Что вы бы изменили в своей жизни, зная то, что знаете?", en: "What would you change in your life knowing what you know?" },
  { chapter: "wisdom", ru: "Какой мудрец или философ вас вдохновляет?", en: "What sage or philosopher inspires you?" },
  { chapter: "wisdom", ru: "Что значит стареть мудро?", en: "What does it mean to age wisely?" },
  { chapter: "wisdom", ru: "Какой главный урок вы оставите потомкам?", en: "What main lesson will you leave for descendants?" },

  // ════════════════════════════════════════
  // MEMORIES (84 вопроса)
  // ════════════════════════════════════════
  { chapter: "memories", ru: "Какой звук или запах вы запомнили сегодня?", en: "What sound or smell do you remember from today?" },
  { chapter: "memories", ru: "Что вы хотите запомнить об этом дне?", en: "What do you want to remember about this day?" },
  { chapter: "memories", ru: "Какую книгу или фильм вы хотели бы пережить заново?", en: "What book or movie would you want to experience again?" },
  { chapter: "memories", ru: "Какое воспоминание греет вас в трудные дни?", en: "What memory warms you on hard days?" },
  { chapter: "memories", ru: "Какой момент вы запомнили в мельчайших деталях?", en: "What moment do you remember in finest detail?" },
  { chapter: "memories", ru: "Какой запах мгновенно переносит вас в прошлое?", en: "What smell instantly takes you to the past?" },
  { chapter: "memories", ru: "Какое первое воспоминание вы помните?", en: "What is your earliest memory?" },
  { chapter: "memories", ru: "Какой момент счастья вы хотите сохранить?", en: "What moment of happiness do you want to preserve?" },
  { chapter: "memories", ru: "Какую фотографию вы хранили бы, если бы осталась одна?", en: "What photo would you keep if only one remained?" },
  { chapter: "memories", ru: "Какой вкус возвращает вас в детство?", en: "What taste takes you back to childhood?" },
  { chapter: "memories", ru: "Какой день вы хотели бы прожить ещё раз?", en: "What day would you want to live again?" },
  { chapter: "memories", ru: "Какое событие в стране или мире вы помните лично?", en: "What national or world event do you remember personally?" },
  { chapter: "memories", ru: "Какая мелодия связана с важным воспоминанием?", en: "What melody is connected to an important memory?" },
  { chapter: "memories", ru: "Какой момент вы пережили вместе с кем-то близким?", en: "What moment did you share with someone close?" },
  { chapter: "memories", ru: "Какой праздник вы помните ярче всего?", en: "What celebration do you remember most vividly?" },
  { chapter: "memories", ru: "Какое место существует только в вашей памяти?", en: "What place exists only in your memory?" },
  { chapter: "memories", ru: "Какой голос вы помните спустя годы?", en: "Whose voice do you remember years later?" },
  { chapter: "memories", ru: "Какой момент разлуки вы помните?", en: "What moment of parting do you remember?" },
  { chapter: "memories", ru: "Какой подарок вы помните из прошлого?", en: "What gift do you remember from the past?" },
  { chapter: "memories", ru: "Какой смешной случай вы вспоминаете с улыбкой?", en: "What funny incident do you recall with a smile?" },
  { chapter: "memories", ru: "Какой рассвет или закат вы запомнили?", en: "What sunrise or sunset do you remember?" },
  { chapter: "memories", ru: "Какое воспоминание вы хотите передать детям?", en: "What memory do you want to pass to your children?" },
  { chapter: "memories", ru: "Какой момент тишины вы помните?", en: "What moment of silence do you remember?" },
  { chapter: "memories", ru: "Какая деталь прошлого удивляет вас?", en: "What detail from the past surprises you?" },
  { chapter: "memories", ru: "Какой первый день на новом месте вы помните?", en: "What first day at a new place do you remember?" },
  { chapter: "memories", ru: "Какой момент прощания вы помните?", en: "What farewell moment do you remember?" },
  { chapter: "memories", ru: "Какое воспоминание вы боитесь забыть?", en: "What memory are you afraid of forgetting?" },
  { chapter: "memories", ru: "Какой исторический момент вы застали?", en: "What historical moment did you witness?" },
  { chapter: "memories", ru: "Какой аромат из детства вы ищете до сих пор?", en: "What childhood aroma do you still search for?" },
  { chapter: "memories", ru: "Какой момент казался обычным, но стал особенным?", en: "What moment seemed ordinary but became special?" },
  { chapter: "memories", ru: "Какое воспоминание связано с водой — рекой, морем, дождём?", en: "What memory is connected to water — river, sea, rain?" },
  { chapter: "memories", ru: "Какой разговор вы помните слово в слово?", en: "What conversation do you remember word for word?" },
  { chapter: "memories", ru: "Какой предмет хранит для вас историю?", en: "What object holds a story for you?" },
  { chapter: "memories", ru: "Какой момент из прошлого вы видите, закрыв глаза?", en: "What moment from the past do you see when you close your eyes?" },
  { chapter: "memories", ru: "Какое ощущение вы помните — ветер, тепло, холод?", en: "What sensation do you remember — wind, warmth, cold?" },
  { chapter: "memories", ru: "Какой последний раз вы помните — последний день, встреча?", en: "What 'last time' do you remember — last day, last meeting?" },

  // ════════════════════════════════════════
  // REFLECTIONS (84 вопроса)
  // ════════════════════════════════════════
  { chapter: "reflections", ru: "Какая мысль не покидала вас весь день?", en: "What thought stayed with you all day?" },
  { chapter: "reflections", ru: "Что бы вы хотели сказать себе утром?", en: "What would you tell your morning self?" },
  { chapter: "reflections", ru: "Что вас удивило в последнее время?", en: "What surprised you recently?" },
  { chapter: "reflections", ru: "Кто сегодня вас вдохновил?", en: "Who inspired you today?" },
  { chapter: "reflections", ru: "Как вы изменились за последний год?", en: "How have you changed in the last year?" },
  { chapter: "reflections", ru: "Что бы вы сделали по-другому на этой неделе?", en: "What would you do differently this week?" },
  { chapter: "reflections", ru: "Какой страх вы преодолели?", en: "What fear did you overcome?" },
  { chapter: "reflections", ru: "О чём вы сожалеете?", en: "What do you regret?" },
  { chapter: "reflections", ru: "Какой момент заставил вас задуматься?", en: "What moment made you think deeply?" },
  { chapter: "reflections", ru: "Что вы поняли о себе недавно?", en: "What did you understand about yourself recently?" },
  { chapter: "reflections", ru: "Какое решение было самым правильным?", en: "What decision was the most right?" },
  { chapter: "reflections", ru: "Что бы вы хотели отпустить?", en: "What would you want to let go of?" },
  { chapter: "reflections", ru: "Как вы справляетесь со стрессом?", en: "How do you cope with stress?" },
  { chapter: "reflections", ru: "Что заставляет вас чувствовать себя живым?", en: "What makes you feel alive?" },
  { chapter: "reflections", ru: "Какой вопрос вы задаёте себе чаще всего?", en: "What question do you ask yourself most often?" },
  { chapter: "reflections", ru: "Что значит для вас покой?", en: "What does peace mean to you?" },
  { chapter: "reflections", ru: "Какой период жизни вы считаете лучшим?", en: "What period of life do you consider the best?" },
  { chapter: "reflections", ru: "Что бы вы хотели изменить в себе?", en: "What would you want to change about yourself?" },
  { chapter: "reflections", ru: "Какой момент показал вам вашу силу?", en: "What moment showed you your strength?" },
  { chapter: "reflections", ru: "О чём вы думаете перед сном?", en: "What do you think about before sleep?" },
  { chapter: "reflections", ru: "Какой выбор определил вашу жизнь?", en: "What choice defined your life?" },
  { chapter: "reflections", ru: "Что вы чувствуете, когда смотрите на своё отражение?", en: "What do you feel when you look at your reflection?" },
  { chapter: "reflections", ru: "Какой совет вы бы дали себе вчерашнему?", en: "What advice would you give yesterday's you?" },
  { chapter: "reflections", ru: "Что для вас значит дом?", en: "What does home mean to you?" },
  { chapter: "reflections", ru: "Какой момент научил вас благодарности?", en: "What moment taught you gratitude?" },
  { chapter: "reflections", ru: "Как вы относитесь к переменам?", en: "How do you feel about change?" },
  { chapter: "reflections", ru: "Что делает вас — вами?", en: "What makes you — you?" },
  { chapter: "reflections", ru: "Какой урок повторяется в вашей жизни?", en: "What lesson keeps repeating in your life?" },
  { chapter: "reflections", ru: "Что вы поняли о времени?", en: "What did you understand about time?" },
  { chapter: "reflections", ru: "Какой день был переломным в вашей жизни?", en: "What day was a turning point in your life?" },
  { chapter: "reflections", ru: "Что значит для вас быть собой?", en: "What does it mean to be yourself?" },
  { chapter: "reflections", ru: "Какой момент тишины изменил вас?", en: "What moment of silence changed you?" },
  { chapter: "reflections", ru: "Что вы откладываете на потом?", en: "What do you keep putting off?" },
  { chapter: "reflections", ru: "Какой разговор с собой вы ведёте?", en: "What conversation do you have with yourself?" },
  { chapter: "reflections", ru: "Что бы вы написали в письме потомкам?", en: "What would you write in a letter to descendants?" },
  { chapter: "reflections", ru: "Какой момент заставил вас заплакать от счастья?", en: "What moment made you cry from happiness?" },
  { chapter: "reflections", ru: "Что вы узнали о мире за свою жизнь?", en: "What did you learn about the world in your lifetime?" },
  { chapter: "reflections", ru: "Как вы хотите провести остаток жизни?", en: "How do you want to spend the rest of your life?" },
  { chapter: "reflections", ru: "Что было бы написано на последней странице вашей книги?", en: "What would be written on the last page of your book?" },
  { chapter: "reflections", ru: "Какой след вы хотите оставить на земле?", en: "What mark do you want to leave on earth?" },
];

// Chapter labels for display
export const chapterLabels: Record<string, Record<string, string>> = {
  ru: {
    childhood: "Детство",
    family: "Семья",
    career: "Карьера",
    values: "Ценности",
    dreams: "Мечты",
    travel: "Путешествия",
    gratitude: "Благодарность",
    wisdom: "Мудрость",
    daily_life: "Повседневность",
    relationships: "Отношения",
    memories: "Воспоминания",
    reflections: "Размышления",
  },
  en: {
    childhood: "Childhood",
    family: "Family",
    career: "Career",
    values: "Values",
    dreams: "Dreams",
    travel: "Travel",
    gratitude: "Gratitude",
    wisdom: "Wisdom",
    daily_life: "Daily Life",
    relationships: "Relationships",
    memories: "Memories",
    reflections: "Reflections",
  },
};

// Chapter order for book generation
export const chapterOrder = [
  "childhood",
  "family",
  "relationships",
  "career",
  "daily_life",
  "travel",
  "dreams",
  "values",
  "gratitude",
  "wisdom",
  "memories",
  "reflections",
];

// ── Question selection ──

export function getTodayQuestion(lang: "ru" | "en"): { text: string; chapter: string } {
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000
  );
  const q = questionPool[dayOfYear % questionPool.length];
  return { text: q[lang], chapter: q.chapter };
}

export function getRandomQuestion(lang: "ru" | "en", excludeText?: string): { text: string; chapter: string } {
  const filtered = excludeText
    ? questionPool.filter((q) => q[lang] !== excludeText)
    : questionPool;
  const q = filtered[Math.floor(Math.random() * filtered.length)];
  return { text: q[lang], chapter: q.chapter };
}
